dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - psql -c "create user decide with password 'decide2020'" 
  - psql -c "create database decidedb owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python ./manage.py test
deploy:
   provider: heroku
   app: decidepruebajossanrui5
   strategy: git
   apikey: $HEROKU_AUTH_TOKEN
   on:
     branch: master

if: branch = master

